### ISSUE TITLE
How to Compute mAP

### ISSUE THREAD

**Issue by mymuli** [bbenligiray/rml-cnn#2]
https://github.com/bbenligiray/rml-cnn/blob/d3f9f28d43862c63558a59b4cc2f63f5e8948e07/metrics.py#L64
When I calculate mAP with labels=[[1,0,1,0,0,0,0,1], [0,1,0,0,0,0,0,0,0,1,0],preds=[[0.6,0.2,0.7,0.3,0.2,0.3,0.4,0.3],  [0.2,0.8,0.1,0.2,0.3,0.4,0.7,0.3]], the result is NAN.

 I would like to ask what is the value of the parameter labels of function calculate_mAP (labels, preds)?

**Comment by bbenligiray** [comment]
The labels for your second image is for 11 classes instead of 8, I'm guessing that's a mistake. I deleted the last three labels:
```
labels = np.array([1,0,1,0,0,0,0,1,0,1,0,0,0,0,0,0]).reshape(2,8)
preds = np.array([0.6,0.2,0.7,0.3,0.2,0.3,0.4,0.3,0.2,0.8,0.1,0.2,0.3,0.4,0.7,0.3]).reshape(2,8)
print(calculate_mAP(labels, preds))
```
Prints 37.5

**Comment by mymuli** [comment]
Thank you very much,First !
https://github.com/bbenligiray/rml-cnn/blob/d3f9f28d43862c63558a59b4cc2f63f5e8948e07/metrics.py#L55
 ground_truth = labels[:, ind_class]  gets the values for each column，
np.sum(ground_truth)  is the sum of each column，
labels = np.array([1,0,1,0,0,0,0,1,0,1,0,0,0,0,0,0]).reshape(2,8) 
 ——> [[1,0,1,0,0,0,0,1],
             [0,1,0,0,0,0,0,0]],
当 ground_truth=[0，0], np.sum(ground_truth)=0, rec = tp / np.sum(ground_truth) is NAN
This is where I am confused. Could you explain it?

**Comment by bbenligiray** [comment]
That function is the rewrite of the function below in Python, so I would consider asking its main author:
https://github.com/zhufengx/SRN_multilabel/blob/master/tools/AP_VOC.m

However, I think the main problem is that you are trying to calculate AP for classes that you have no positive example of. For example the label for your 4th class is 0 for both examples, which doesn't make sense. Why would you use a class if none of your examples have it?

**Comment by mymuli** [comment]
I understand it. Thank you very much.
